### ISSUE TITLE
Noise cleanup-branch example, go run error undefined

### ISSUE THREAD

**Issue by SgtRumpel** [perlin-network/noise#260] opened 2019-11-21 07:04 UTC
I tried to compile the 4 example in the cleanup-brach, but there a fu ction like registerroutemessageserver but he doesn't find this function, can you help me please.

**Comment by iwasaki-kenta** [comment] 2020-01-29 13:08
Closing. Refer to #266 as it no longer has a hard dependency on grpc or protobuf (which is the cause for this error).

**Closed by iwasaki-kenta** 2020-01-29 13:08 UTC
